export enum ScreenNames {
  INITIAL = 'initial',
  AUTH = 'auth',
  LOGIN = 'login',
  SIGN_UP_PREVIEW = 'sign_up_preview',
  SIGN_UP = 'sign_up',
  FORGOT_PASSWORD = 'forgot_password',
  CODE_CHECK = 'code_check',
  RESET_PASSWORD = 'reset_password',
  PASSWORD_CHANGED = 'password_changed',
  LANGUAGE_SELECT = 'language_select',
  DASHBOARD = 'dashboard',
  COURSES = 'courses',
  TABS = 'tabs',
  PROFILE = 'profile',
  MAIL = 'mail',
}
