import {StyleSheet} from 'react-native';
import {mainBlue} from '../../../../../../assets/colors';

export default StyleSheet.create<any>({
  itemContainer: {
    flexDirection: 'row',
    backgroundColor: 'white',
    borderRadius: 10,
    shadowRadius: 1,
    marginHorizontal: 4,
    shadowOpacity: 0.3,
    shadowColor: 'rgba(0,0,0,0.4)',
    shadowOffset: {width: 0, height: 4},
    marginTop: 10,
    marginBottom: 7,
    elevation: 5,
  },
  logo: {width: '33%', height: '100%', borderRadius: 10, alignSelf: 'center'},
  itemContent: {
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    paddingLeft: 10,
    paddingRight: 8,
    width: '67%',
    paddingBottom: 11,
    paddingTop: 8,
    // paddingHorizontal: 10,
  },
  title: {fontFamily: 'Poppins-Regular', fontSize: 16},
  author: {
    fontFamily: 'Inter-Regular',
    fontSize: 12,
    color: '#A6A6A6',
    paddingVertical: 4,
  },
  progressContainer: {
    // flexDirection: 'row',
    position: 'relative',
    borderRadius: 100,
    height: 8,
    width: '100%',
  },
  fullLine: {
    backgroundColor: 'rgba(0,0,0,0.1)',
    width: '100%',
    height: 8,
    position: 'absolute',
    borderRadius: 100,
  },
  progress: (completed: number) => ({
    backgroundColor: mainBlue,
    position: 'absolute',
    height: 4,
    top: 2,
    borderRadius: 100,
    width: `${completed}%`,
  }),
  completedText: {
    fontFamily: 'Poppins-Medium',
    fontSize: 12,
    paddingTop: 3,
  },
  generalInfo: {flex: 1},
  completedWrapper: {paddingTop: 15},
});
